### ISSUE TITLE
rename column names to english w/ caps

### ISSUE THREAD

**Issue by skipmcgee** [skipmcgee/wind-forecast#10]
use the rename sql feature or implement in the thead expansion (better in the latter so as to not create issues with subsequent queries?)

**Comment by skipmcgee** [comment]
done for models

**Comment by skipmcgee** [comment]
to-do: sensors, forecasts and readings

**Comment by tjnorred** [comment]
Addressed in [4a8eb79](https://github.com/skipmcgee/wind-forecast/commit/4a8eb7909de15e4c0041700f10cf09b7a56dc284). Please review the headers for accuracy.

**Comment by skipmcgee** [comment]
So your conversions look good. However, we may want to reconsider and do this conversion in the jinja template. The crud operations aren't working now because the html template button hrefs were based off the previous attribute names - so for example locationID is now ID. So we can either revise all the html templates to use the new attribute names (seems like not the best because some of the names have spaces?) or we do a dict lookup in the jinja template to remap for display only, leaving the object passed to the template unchanged and therefore accessible?

**Comment by skipmcgee** [comment]
implemented with https://github.com/skipmcgee/wind-forecast/commit/a6c2320228d311b6c18466531d121fcecc82a848

**Comment by skipmcgee** [comment]
let me know what you think / we can probably close this?

**Comment by tjnorred** [comment]
Just remove the alias from the ID columns. No need to store the column headers in two data structures.

For example, sensors would look like this:

sensors.html
```
{% if key != 'sensorID' %}
<th scope="col" data-field="{{ key }}" data-filter-control="input">{{ key }}</th>
{% endif %}
```
app.py
```
SELECT
            sensorID, 
            sensorName AS 'Name', 
            sensorAPIKEY AS 'API Key', 
            sensorNumber AS 'Number', 
            locationLatitude AS 'Latitude', 
            locationLongitude AS 'Longitude', 
            locationAltitude AS 'Altitude'
        FROM 
            Sensors
        JOIN Locations ON Sensors.sensorLocationID = Locations.locationID
        ORDER BY
            sensorName DESC;
```

**Comment by skipmcgee** [comment]
I think separating the display from data plane here is good for a couple of reasons. Keeping the data plane consistent is nice for the app development, troubleshooting, etc. First, it isn’t just the id attribute that we would have to not rename, we are also already filtering by other attributes elsewhere in the templates that we would have to change too.  Second, the rename breaks things like the dot syntax due to spaces which is a convenient way to access values. Spaces look good in the display plane so I agree we should use them…I think ideally we could turn the individual dictionaries into one large hash table that lives in its own class - then we gain the ability to change the display of every attribute we possess across the site from a single location.This could be a class we build the classes for the views off of so that the hash table is inherently accessible to those classes.On May 14, 2024, at 11:48 PM, TJ Norred ***@***.***> wrote:﻿
Just remove the alias from the ID columns. No need to store the column headers in two data structures.
For example, sensors would look like this:
sensors.html
{% if key != 'sensorID' %}
<th scope="col" data-field="{{ key }}" data-filter-control="input">{{ key }}</th>
{% endif %}

app.py
SELECT
            sensorID, 
            sensorName AS 'Name', 
            sensorAPIKEY AS 'API Key', 
            sensorNumber AS 'Number', 
            locationLatitude AS 'Latitude', 
            locationLongitude AS 'Longitude', 
            locationAltitude AS 'Altitude'
        FROM 
            Sensors
        JOIN Locations ON Sensors.sensorLocationID = Locations.locationID
        ORDER BY
            sensorName DESC;

**Comment by tjnorred** [comment]
That sounds like a lot of work just to display the column headers, tho. Alias don't actually change the data. 

Also, if the schema ever changes, then you have to update the hash table every time. Where with alias we only have to update the SQL query.

I tested my proposal last night and both the delete and edit functionalities still worked as they should. 

The attributes in the forms are being populated with a different function/query within app.py. 

Read (Using alias to present clean headers)

```
@app.route('/sensors', methods=["GET"])
def sensors():
    '''View for the Sensors Admin Page'''

    if request.method == "GET":
        sensor_query = '''
        SELECT
            sensorID, 
            sensorName AS 'Name', 
            sensorAPIKEY AS 'API Key', 
            sensorNumber AS 'Number', 
            locationLatitude AS 'Latitude', 
            locationLongitude AS 'Longiude', 
            locationAltitude AS 'Altitude'
        FROM 
            Sensors
        JOIN Locations ON Sensors.sensorLocationID = Locations.locationID
        ORDER BY
            sensorName DESC;
        '''
        sensor_obj = db.execute_query(db_connection=db_connection, query=sensor_query)
        sensor_results = sensor_obj.fetchall()
        if DEBUG:
            logger.info(sensor_results)
        return render_template("pages/sensors.html", sensors=sensor_results, sensor_dict=sensor_dict)
    elif request.method == "POST":
        return redirect("/")
        '''
        query_results = db.execute_query(db_connection=db_connection, query=query, query_params={'sensorID': sensorID}).fetchall()
        if DEBUG:
            logger.info(f"edit sensor get: {query_results}")

        return render_template("edit/sensor.html", specific_sensor=query_results)
```


Update (Headers can still be referenced by dot attribute)
```
@app.route("/edit/sensor/<int:sensorID>", methods=["POST", "GET"])
def update_sensor(sensorID):
    '''API Route to update a sensor'''

    sensorID = escape(sensorID)

    if DEBUG:
        logger.info(f"Edit sensor post: {sensorID}")

    if request.method == "GET":
        query = '''
        SELECT 
            * 
        FROM 
            Sensors
        INNER JOIN 
            Locations ON Sensors.sensorLocationID = Locations.locationID
        WHERE 
            Sensors.sensorID = %(sensorID)s;
        '''
        query_results = db.execute_query(db_connection=db_connection, query=query, query_params={'sensorID': sensorID}).fetchall()
        if DEBUG:
            logger.info(f"edit sensor get: {query_results}")

        return render_template("edit/sensor.html", specific_sensor=query_results)
```

Either way works, tho.

**Comment by tjnorred** [comment]
Let's just move forward with your solution since it was already implemented. We can probably close this issue.

**Comment by skipmcgee** [comment]
ok thanks, i added a class data set to this
