### ISSUE TITLE
Separate Update Responsibilities

### ISSUE THREAD

**Issue by tjnorred** [skipmcgee/wind-forecast#15]
Currently, if you update a sensor, you have the ability to directly update the fields at a location as well. 

I think we should present the sensor fields that can be updated and include a drop-down to add an existing location. This should help prevent overwriting data by accident. 

If a user needs to choose a location that is not currently in the db, then they go to the locations table and add that location. Come back and select that location from the drop-down. 

If the location is available, but a data point in incorrect, then they go to the locations table and edit that location.

Sandia Peak Tempest and Sandia Peak Holfuy both share the same location ID, so when you click edit on either and update say the altitude, it isn't exactly clear that the change will impact both sensors in the table. 

Just an idea to make the user experience a little bit better. 

![image](https://github.com/skipmcgee/wind-forecast/assets/23566817/5dd91c56-8085-443b-b666-3e994bed221c)

![image](https://github.com/skipmcgee/wind-forecast/assets/23566817/648fa6d9-3c60-4769-bc7c-8015730adb2d)

**Comment by skipmcgee** [comment]
yeah i think this is a great idea! or we make those fields not editable. need to do same lookups for forecast and reading date (because they matter when)

**Comment by skipmcgee** [comment]
also i think this is in the requirements doc: "Does at least one SELECT utilize a search/filter with a dynamically populated list of properties?
