### ISSUE TITLE
Forecast Date Columns

### ISSUE THREAD

**Issue by tjnorred** [skipmcgee/wind-forecast#18]
There's currently two date columns in forecasts. Do we need both?

![image](https://github.com/skipmcgee/wind-forecast/assets/23566817/cbeefdbe-3f2a-4b74-8934-671a70e3babe)

![image](https://github.com/skipmcgee/wind-forecast/assets/23566817/70b216bf-eb51-4f63-8d85-73e33a01f9d1)

**Comment by skipmcgee** [comment]
So the one is the date the forecast was created, the other is the date the forecast is for. So yeah I think we need bothThanks,SkipOn May 19, 2024, at 12:13 AM, TJ Norred ***@***.***> wrote:﻿
There's currently two date columns in forecasts. Do we need both?
image.png (view on web)
image.png (view on web)
