### ISSUE TITLE
add a confirmation popup for delete events

### ISSUE THREAD

**Issue by skipmcgee** [skipmcgee/wind-forecast#2]
need a confirmation popup for the user to confirm deletion

**Comment by skipmcgee** [comment]
we could do this in flash?

**Comment by skipmcgee** [comment]
can't do in flash, but i added a confirmation of deletion message. may need to consider popup

**Comment by tjnorred** [comment]
We can add HTMX for form validation. https://htmx.org/attributes/hx-prompt/

Alternatively, https://flask.palletsprojects.com/en/2.3.x/patterns/wtforms/

**Comment by skipmcgee** [comment]
great ideas! yeah i'll scope those out!

**Comment by skipmcgee** [comment]
I think the WTForms one looks awesome and adds some better validation hooks as well. May take a bit longer to implement but seems reasonable

**Comment by tjnorred** [comment]
e366a71
