### ISSUE TITLE
need results plotting and comparison

### ISSUE THREAD

**Issue by skipmcgee** [skipmcgee/wind-forecast#8]
would like to actually write an alg to do the comparison to for the forecast to reading data.

display this with pyplot or similar?

**Comment by skipmcgee** [comment]
this is not functionality required for this assignment / lowest priority

**Comment by tjnorred** [comment]
Some options to check out:

- https://dash.plotly.com/
- https://streamlit.io/

**Comment by skipmcgee** [comment]
great ideas, will scope those out!!

**Comment by skipmcgee** [comment]
https://github.com/skipmcgee/wind-forecast/commit/5822d1e16eec631f5b8a45715610aa79ff4bf650

added some initial plots, need to tweak and improve but will open another issue for that
