### ISSUE TITLE
DDL changes to consider

### ISSUE THREAD

**Issue by skipmcgee** [skipmcgee/wind-forecast#9]
After testing deletions, i think i may need to change the ddl to allow update and deletions:

MySQLdb.IntegrityError: (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`cs340`.`Readings`, CONSTRAINT `fk_Readings_Sensors1` FOREIGN KEY (`readingSensorID`) REFERENCES `Sensors` (`sensorID`) ON DELETE NO ACTION ON UPDATE NO ACTION)')

MySQLdb.IntegrityError: (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`cs340`.`Forecasts`, CONSTRAINT `fk_Forecasts_Models` FOREIGN KEY (`forecastModelID`) REFERENCES `Models` (`modelID`) ON DELETE NO ACTION ON UPDATE NO ACTION)')

**Comment by skipmcgee** [comment]
this might be better accomplished by joins before the delete or update?

**Comment by tjnorred** [comment]
We don't need joins to accomplish this.   https://canvas.oregonstate.edu/courses/1958399/pages/exploration-mysql-cascade?module_item_id=24181838

Just need to change the ON DELETE NO ACTION to either CASCADE (delete the referenced object in the other table) or SET NULL.

**Comment by tjnorred** [comment]
608e55d

**Comment by skipmcgee** [comment]
nice, we have a few small bugs we still need to work out where if you delete some objects it creates other issues, but i think this is great progress!

**Comment by skipmcgee** [comment]
should be completed with https://github.com/skipmcgee/wind-forecast/commit/acdf2148b874e360923f11fc1ad0cbff97fb5d92
